### ISSUE TITLE
onboarding failed: no possibility to retrieve response body

### ISSUE THREAD

**Issue by oliverrahner** [DKE-Data/agrirouter-api-cpp#12]
When an error occurs during onboarding, there is no possibility to retrieve the actual HTTP response body for further investigation.

**Comment by ThomasMeyerdirks** [comment]
This is already fixed in the dev branch and will be added to the master with the next merge. 

We still have to finish the MQTT implementation, then we have a clean state of the lib.

**Comment by ThomasMeyerdirks** [comment]
Done with:
https://github.com/DKE-Data/agrirouter-api-cpp/releases/tag/v2.0
