### ISSUE TITLE
Direct Sending to Endpoint ID does not work

### ISSUE THREAD

**Issue by JulianImwalle** [DKE-Data/agrirouter-api-cpp#4]
Currently the usage of direct sending does not work with the agriRouterClientTest in CPP:
./AgrirouterClientTest --recipient=RECIPIENT_END_POINT_ID --taskdata="PATH_TO_MY_FILE//MY_FILE.zip"
lead to response message:
Message callback (event 212)
Envelope (size 215): {
 "responseCode": 400,
 "type": "ACK_WITH_FAILURE",
 "applicationMessageId": "249d7e0e-c26e-447b-8c09-8b4dce954ed0",
 "messageId": "f2902be4-8b0d-464c-beb5-f713b7f4206f",
 "timestamp": "2020-09-01T08:32:31.466Z"
}
Payload type_url: "types.agrirouter.com/agrirouter.commons.Messages", payload size: 82
Messages, type_url: types.agrirouter.com/agrirouter.commons.Messages
value: {
 "messages": [
  {
   "message": "No recipients have been identified for iso:11783:-10:taskdata:zip.",
   "messageCode": "VAL_000004"
  }
 ]
}
To Test the agriRouterClientTest I use the agriRouter InOut-Tool.
The publishing of taskdata
 ./AgrirouterClientTest --taskdata="PATH_TO_MY_FILE//MY_FILE.zip"
however works fine, if an endpoint (in my case the InOut-Tool) sub scripted to the kind of data to be published.
If the InOut-Tool does not subscribe to any data, i get the same error for publishing a taskdata and sending the taskdata directly to the InOut-Tool.

The filtered endpoint list says, that the direct sending of a taskdata should work:
Payload type_url: "types.agrirouter.com/agrirouter.response.payload.account.ListEndpointsResponse", payload size: 159
ListEndpointsResponse: {
 "endpoints": [
  {
   "endpointId": "RECIPIENT_END_POINT_ID",
   "endpointName": "InOut-Tool - 2020-08-31, 13:11:50",
   "endpointType": "application",
   "status": "active",
   "messageTypes": [
    {
     "technicalMessageType": "iso:11783:-10:taskdata:zip",
     "direction": "SEND_RECEIVE"
    }
   ],
   "externalId": "INOUTEXTERNALID"
  }
 ]
}

**Comment by doekermk** [comment]
The last sentence of the [general message exchange](https://github.com/DKE-Data/agrirouter-interface-documentation/blob/edd5ded1f9b0bdc4f71009835b74214db91e00b7/docs/message-exchange.adoc#general-message-exchange) says
> If messages are sent directly and recipients are mentioned in the address lists, they are delivered, if the endpoint supports this message type and if there is a routing allowing the delivery.

@Frank-Wiebeler can you clarify if the expected behaviour (sending data directly to an endpoint works without a subscription) is correct?

**Comment by Frank-Wiebeler** [comment]
Direct messages are delivered without subscription.

Issue is a minor bug in the library; fixed with PR #5 

@doekermk  Please review and merge

**Comment by doekermk** [comment]
Thanks Frank, issue is fixed
