### ISSUE TITLE
Memory corruption bug

### ISSUE THREAD

**Issue by plum-s** [DKE-Data/agrirouter-api-cpp#8]
There are several occurences of wrong memory allocation in the library.
This can cause crashes.

```
char *tmp = new char[size];
...
tmp[size] = '\0';
```

The size of the char array needs to be size + 1 in order to be able to write to tmp[size].

**Comment by ThomasMeyerdirks** [comment]
This is already fixed in the dev branch and will be added to the master with the next merge. 

We still have to finish the MQTT implementation, then we have a clean state of the lib.

**Comment by ThomasMeyerdirks** [comment]
Done with:
https://github.com/DKE-Data/agrirouter-api-cpp/releases/tag/v2.0
